### ISSUE TITLE
Add a recordatory to save constantly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hernandcb/ccafs-ap#161]
```
Due to the users can forget save the information, we can show them a reminder 
every 20 minutes or so.
```

Original issue reported on code.google.com by `carvajal.hernandavid@gmail.com` on 25 Oct 2013 at 3:07

**Comment by hernandcb** [comment]
I am going to close this issue given that the issue #159 is about adding an auto save functionality to the platform.
