### ISSUE TITLE
Indicate who commisioned the activities

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hernandcb/ccafs-ap#178]
```
So far, a new activity can be marked as commisioned but there is no record of 
who made it. 
This information can be very useful.
```

Original issue reported on code.google.com by `carvajal.hernandavid@gmail.com` on 20 Jan 2014 at 1:35

**Comment by hernandcb** [comment]
I am going to close this issue because the flagship version of the platform doesn't use the concept of commissioned activities
