### ISSUE TITLE
Specify the total budget for multi anual activities

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hernandcb/ccafs-ap#230]
```
For activities that will take more than one year the user should specify the 
total budget and break down the amount for each year. 

```

Original issue reported on code.google.com by `carvajal.hernandavid@gmail.com` on 15 Apr 2014 at 1:05

**Comment by hernandcb** [comment]
In the flagship version of the platform we have implemented an improved budget section where you can enter the budget per year and visualize the total.

See image: 
![image](https://cloud.githubusercontent.com/assets/4978907/6738037/70de247c-ce3d-11e4-9037-898cec1421e5.png)
