### ISSUE TITLE
The gender integration info shouldn't be copied from previous years.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hernandcb/ccafs-ap#234]
```
When the user indicates that an activity from previous years is continuation 
from another, the information related to the gender integration shouldn't be 
copied.
```

Original issue reported on code.google.com by `carvajal.hernandavid@gmail.com` on 15 Apr 2014 at 4:16

**Comment by hernandcb** [comment]
This issue was opened for the previous version of the platform (Logframes).
As the logframes version of the platform doesn't continue the activities this issue is not valid any more.
