### ISSUE TITLE
Add a summary about activities

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hernandcb/ccafs-ap#241]
```
The platform should generate a summary about the activities. It is needed add 
filters to know which activities will be included in the summary.
```

Original issue reported on code.google.com by `carvajal.hernandavid@gmail.com` on 15 Apr 2014 at 6:56

**Comment by hernandcb** [comment]
In the flagships version of the platform we have developed a functionality to download the information of the projects.

![image](https://cloud.githubusercontent.com/assets/4978907/6735213/ded63216-ce2a-11e4-9a08-90f1e7a98096.png)
