### ISSUE TITLE
Add the URL for all partners contained in the database.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hernandcb/ccafs-ap#253]
```
Some person will look for the website of each partner in the database.
```

Original issue reported on code.google.com by `carvajal.hernandavid@gmail.com` on 15 Apr 2014 at 7:51

**Comment by hernandcb** [comment]
Perhaps we can find someone in the communications team that help us with this task.

I am going to close this issue given that is not necessary at the moment.
