### ISSUE TITLE
Allow to the users change the number of activities showed in the activities tables.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hernandcb/ccafs-ap#255]
```
Actually, the activities table only shows twenty rows, it is needed enable the 
option of the plugin that allows to the user select how many activities they 
want to see.
```

Original issue reported on code.google.com by `carvajal.hernandavid@gmail.com` on 15 Apr 2014 at 7:57

**Comment by hernandcb** [comment]
It was added an option to change the size of the table.

![image](https://cloud.githubusercontent.com/assets/4978907/6735112/1e7d3942-ce2a-11e4-8d32-1f097d7f5c09.png)
