### ISSUE TITLE
Create page to ask the contact people of projects

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hernandcb/ccafs-ap#262]
```
This page will ask what institutions will be involved with the project and who 
are the contact persons for each institution.
```

Original issue reported on code.google.com by `carvajal.hernandavid@gmail.com` on 16 Apr 2014 at 2:16

**Comment by hernandcb** [comment]
We have improved the partners section to ask who is the person responsible of the project, what institutions will be partners and who will be the contact person for each institution. 

See image:

![image](https://cloud.githubusercontent.com/assets/4978907/6735075/dbae4cf0-ce29-11e4-8e79-451a9edb4caa.png)
