### ISSUE TITLE
Create page to ask the information about IDOs for each project

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hernandcb/ccafs-ap#263]
```
In this page the user should indicate to which IDOs the project will contribute 
and explain how they will do it.
```

Original issue reported on code.google.com by `carvajal.hernandavid@gmail.com` on 16 Apr 2014 at 2:22

**Comment by hernandcb** [comment]
We have developed an outcomes section in the flagships version of the platform where we ask about the IDO. See image:

![image](https://cloud.githubusercontent.com/assets/4978907/6735002/610982c6-ce29-11e4-8a48-3e1b43bb9f3c.png)
