### ISSUE TITLE
Create page to ask the outcome indicators expected for each project

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hernandcb/ccafs-ap#265]
```
In this page the user should specify the outcome indicators that the project 
should reach.
```

Original issue reported on code.google.com by `carvajal.hernandavid@gmail.com` on 16 Apr 2014 at 2:30

**Comment by hernandcb** [comment]
We implemented a project's outcome page where we ask the indicators and the targets of the project.
See image

![image](https://cloud.githubusercontent.com/assets/4978907/6734874/9b2f2b96-ce28-11e4-9e8c-80df31b17078.png)
