### ISSUE TITLE
Create page to ask additional information about the project

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hernandcb/ccafs-ap#266]
```
In this page the user should specify how the project will contribute with the 
following topics:

- Data Management
- Communications
- Social differentiation
- Capacity building
```

Original issue reported on code.google.com by `carvajal.hernandavid@gmail.com` on 16 Apr 2014 at 2:33

**Comment by hernandcb** [comment]
Since the conceptual changes are being discussed I'm not sure if this is needed. 
I'm going to close this issue and will create a new issue if these changes are needed.
