### ISSUE TITLE
Create page to ask the budget of each project

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hernandcb/ccafs-ap#267]
```
This section should ask the total budget of the project, a break down for year 
and the amount of budget that goes to each partner anually
```

Original issue reported on code.google.com by `carvajal.hernandavid@gmail.com` on 16 Apr 2014 at 2:54

**Comment by hernandcb** [comment]
This issue was already solved in the impact pathways of the platform.
See image:

![image](https://cloud.githubusercontent.com/assets/4978907/6734725/c756e0a2-ce27-11e4-8c3c-6e7560afbf68.png)
